---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker (Ansible <2.12).
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: "ansible_version.full is version_compare('2.12', '<')"

- name: Install Docker (Ansible >=2.12).
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
    allow_downgrade: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: "ansible_version.full is version_compare('2.12', '>=')"

- name: Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Check if docker config exists
  stat:
    path: /etc/docker/daemon.json
  register: loaded_docker_daemon_options

- name: Create docker config if it doesn't exist
  copy:
    dest: /etc/docker/daemon.json
    content: "{}"
    mode: 0644
  when: not loaded_docker_daemon_options.stat.exists

- name: Load vars from daemon.json
  slurp:
    src: /etc/docker/daemon.json
  register: imported_vars

- name: Combine local and remote configuration
  set_fact:
    imported_var: "{{ imported_vars.content|b64decode|from_json | default([]) | combine( docker_daemon_options ) }}"

- name: Load updated config to daemon.json
  copy: 
    content: "{{ imported_var | to_nice_json }}" 
    dest: /etc/docker/daemon.json
    mode: 0644
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
